const commentModel = {
    boardIdx: 0,
    userIdx: 0,
    // channelType: "",
    // importantType: "",
    // boardType: "",
    processStatus: "",
    // detailType: "",
    // categoryType: "",
    subject: "",
    subTitle: "",
    content: "",
    // securityCode: "",
    showYn: "Y",
    openYn: "Y",
    boardPwd: "",
    // alimYn: "",
    userNameFirstKo: "",
    userNameLastKo: "",
    userNameFirstEn: "",
    userNameLastEn: "",
    localYn: "",
    email: "",
    gender: "",
    birthYyyy: "",
    birthMm: "",
    birthDd: "",
    interPhoneNumber: "",
    mobile1: "",
    mobile2: "",
    mobile3: "",
    mobileAgency: "",
    fileContent: "",
    userNameKo: "",
    userNameEn: "",
    regUserIdx: 0,
    regUserNameKo: "",
    regUserNameEn: "",
    modUserIdx: 0,
    modUserNameKo: "",
    modUserNameEn: "",
    modDttm: "",
};

export { commentModel };
