const artistModel = {
    peopleIdx: 0,
    profileIdx: 0,
    categoryIdx: 0,
    peopleType: "",
    nameFirstKo: "",
    nameLastKo: "",
    nameFirstCn: "",
    nameLastCn: "",
    nameFirstEn: "",
    nameLastEn: "",
    email: "",
    gender: "",
    birthType: "",
    birthYyyy: "",
    birthMm: "",
    birthDd: "",
    interPhoneNumber: "",
    mobile1: "",
    mobile2: "",
    mobile3: "",
    peopleMemo: "",
    fileContent: "",
    peopleIdxs: [0],
    rowNum: 0,
    useYn: "",
    delYn: "",
    showYn: "",
    userIdx: 0,
    userNameKo: "",
    userNameEn: "",
    regUserIdx: 0,
    regUserNameKo: "",
    regUserNameEn: "",
    regDttm: "",
    modUserIdx: 0,
    modUserNameKo: "",
    modUserNameEn: "",
    modDttm: "",
};

export { artistModel };
